#!/bin/bash
#https://www.boost.org/doc/libs/1_67_0/more/getting_started/unix-variants.html#build-a-simple-program-using-boost
#(4 Build a Simple Program Using Boost)

c++ -I /usr/local/boost_1_67_0 example.cpp -o example
